### ISSUE TITLE
what is gseaParam?

### ISSUE THREAD

**Issue by enricoferrero** [ctlab/fgsea#10]
What is the `gseaParam` argument in `fgsea()`?
The help page just says  "GSEA parameter value" and I couldn't find it in the GSEA docs.
Thanks!

**Comment by assaron** [comment]
All the scores are raised to the power of `gseaParam` in the analysis. In original pape by Subramanian et al (http://www.pnas.org/content/102/43/15545.abstract) it's called exponent p.

**Comment by enricoferrero** [comment]
Thanks @assaron, it might be worth adding that description in the docs for `?fgsea`.
