### ISSUE TITLE
p values not reproducible when running fgsea function despite set.seed

### ISSUE THREAD

**Issue by pforny** [ctlab/fgsea#100]
I keep getting non-reproducible p values (as well as adjusted p values) when running the same code twice.

```
data(examplePathways)
data(exampleRanks)
set.seed(42)

fgseaRes <- fgsea(pathways = examplePathways, 
                  stats    = exampleRanks,
                  minSize  = 15,
                  maxSize  = 500,
                  eps = 0)
head(fgseaRes[order(pval), ], 3)
```

**Run 1:**
                        pathway         pval         padj  log2err        ES
1:           5990980_Cell_Cycle 1.892239e-26 1.108852e-23 1.334497 0.5388497
2:  5990979_Cell_Cycle,_Mitotic 4.234473e-26 1.240701e-23 1.326716 0.5594755
3: 5991851_Mitotic_Prometaphase 4.553106e-18 8.893735e-16 1.095929 0.7253270
        NES size                              leadingEdge
1: 2.695983  369 66336,66977,12442,107995,66442,19361,...
2: 2.772042  317 66336,66977,12442,107995,66442,12571,...
3: 3.001149   82 66336,66977,12442,107995,66442,52276,...

**Run 2:**
                        pathway         pval         padj  log2err        ES
1:  5990979_Cell_Cycle,_Mitotic 1.146880e-26 6.720715e-24 1.342234 0.5594755
2:           5990980_Cell_Cycle 3.138139e-26 9.194748e-24 1.326716 0.5388497
3: 5991851_Mitotic_Prometaphase 4.751702e-18 7.745772e-16 1.095929 0.7253270
        NES size                              leadingEdge
1: 2.728030  317 66336,66977,12442,107995,66442,12571,...
2: 2.658656  369 66336,66977,12442,107995,66442,19361,...
3: 2.942320   82 66336,66977,12442,107995,66442,52276,...

Also when I run the following slightly different code, the p values are not reproducible.

```
data(examplePathways)
data(exampleRanks)
set.seed(42)
fgseaRes <- fgseaSimple(pathways = examplePathways, 
                  stats    = exampleRanks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)
head(fgseaRes[order(pval), ], 3)
```

**Run 1:**
                            pathway        pval     padj        ES      NES
1:               5990980_Cell_Cycle 0.001212121 0.014608 0.5388497 2.683310
2:      5990979_Cell_Cycle,_Mitotic 0.001216545 0.014608 0.5594755 2.760062
3: 5991210_Signaling_by_Rho_GTPases 0.001278772 0.014608 0.4238512 2.018599
   nMoreExtreme size                                leadingEdge
1:            0  369   66336,66977,12442,107995,66442,19361,...
2:            0  317   66336,66977,12442,107995,66442,12571,...
3:            0  231 66336,66977,20430,104215,233406,107995,...

**Run 2:**
                            pathway        pval       padj        ES      NES
1:               5990980_Cell_Cycle 0.001230012 0.01494136 0.5388497 2.695721
2:      5990979_Cell_Cycle,_Mitotic 0.001264223 0.01494136 0.5594755 2.763236
3: 5991210_Signaling_by_Rho_GTPases 0.001344086 0.01494136 0.4238512 2.009793
   nMoreExtreme size                                leadingEdge
1:            0  369   66336,66977,12442,107995,66442,19361,...
2:            0  317   66336,66977,12442,107995,66442,12571,...
3:            0  231 66336,66977,20430,104215,233406,107995,...

Thanks a lot for your help @assaron or anyone!

**Comment by assaron** [comment]
Can you also report result of `set.seed(42); sample.int(10^9, 10)`? Does it stay the same?

**Comment by pforny** [comment]
Thanks @assaron !

Maybe I don't exactly understand the workings of the `set.seed()` function. When I set.seed directly before running the sample.int, then I get reproducible results. But I have to run it each time. This is also true for the fgsea function. Is there a way to set the seed permanently for one session?

```
> set.seed(42)
> sample.int(10^9, 10)
```
 [1] 707850213 155243673 608797924 674280576 892254232 793133412 911798437
 [8] 980229652 966365042 661529475
`> sample.int(10^9, 10)`
 [1] 354059172 602204127 845993477 593211240  16962874  31470890 672636062
 [8] 556429199 160823610 780662052


```
> set.seed(42)
> sample.int(10^9, 10)
```
 [1] 707850213 155243673 608797924 674280576 892254232 793133412 911798437
 [8] 980229652 966365042 661529475
```
> set.seed(42)
> sample.int(10^9, 10)
```
 [1] 707850213 155243673 608797924 674280576 892254232 793133412 911798437
 [8] 980229652 966365042 661529475

**Comment by assaron** [comment]
`set.seed()` sets the state of the random generator, this state is changed when random numbers are generated. So yes, if you want a block of code to be reproducible you have to set seed each time before each run. 

Block:
```
set.seed(42)
fgseaRes <- fgseaSimple(pathways = examplePathways, 
                  stats    = exampleRanks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)
 ```
should be reproducible as a whole. A single call to `fgsea` can not.

**Comment by pforny** [comment]
This clarifies it entirely. Thanks a lot for your help and apologize for the confusion.
