### ISSUE TITLE
fgsea set.seed returns different results on bitbucket server than locally

### ISSUE THREAD

**Issue by ldiao** [ctlab/fgsea#104]
There have been a couple of old reports around set.seed() not producing consistent results but I think what I'm observing is different.

The versions of fgsea I tested include v1.8.0, v1.18.0, and v.1.19.3.

I am writing some unit tests for a workflow that incorporates fgsea. Locally, I can run the following in my console:

set.seed(1111)
fgsea(pathways, gene_ranks, nperm = 10000, nproc = 1)

and obtain the same p-values each time. I first found that different results were obtained when I then ran the unit tests locally, so I then explicitly used set.seed(1111, kind = 'Mersenne-Twister'), which appeared to address that issue.

However, when I pushed my branch to our bitbucket server, the build failed every time, because the p-values obtained were [substantially] different. Interestingly, it wasn't that the p-values were different every time--they were the same each time the unit tests were run on the server, the results were just different from the results I was obtaining (consistently) locally.

We have an renv set up which should match the server build with our local builds, yet the p-value issue remains. The only workaround I have found is to allow p-values to vary by up to 0.1, but that is clearly not ideal.

Any ideas as to what could be going on here?

**Comment by assaron** [comment]
Hi, 

It will be hard to debug. First, could you report the output of the following script both on your local machine and bitbucket server?

```
library(fgsea)
data("examplePathways")
data("exampleRanks")
set.seed(42)
print(sample.int(10^9, 1))
print(fgsea(examplePathways[1:2], exampleRanks, nperm=2000, maxSize=500, nproc=1)$nMoreExtreme)
print(sample.int(10^9, 1))
```

**Comment by ldiao** [comment]
Sure, on the server the results I get are:

707850213
634 831
674280576

Locally I get:

914806044
615 830
641745519

**Comment by ldiao** [comment]
Could this be related to the following: 

https://stackoverflow.com/questions/47199415/is-set-seed-consistent-over-different-versions-of-r-and-ubuntu

We are using different versions of R locally (3.5.X) and on the server (4.+)

**Comment by assaron** [comment]
Oh, you have different R versions. There was a change in the random generator behavior. See https://blog.revolutionanalytics.com/2019/05/whats-new-in-r-360.html

In the recent versions you can get the old behavior by calling `RNGkind(sample.kind="Rounding"))` beforehand. And the new behavior can switched back by setting `RNGkind(sample.kind = "Rejection")`

**Comment by ldiao** [comment]
Agree, I changed the RNGversion and it appears to be working now. Thanks!
