### ISSUE TITLE
p values

### ISSUE THREAD

**Issue by davidlyon3** [ctlab/fgsea#106]
Firstly Thanks for a great R package

Problem:
If I run fgsea two times:

Run 1) first using a pre-ranked gene set and 
Run 2) reverse the ranking of the pre-ranked gene set from Run 1

Question:
should the p-values be the same in Run 1) and Run 2) above or slightly different and why?

I am getting slightly different p-values and was wondering if that's normal .

Thanks in advance

**Comment by vdsukhov** [comment]
Hi @davidlyon3 , 
could you please provide some code example?

**Comment by davidlyon3** [comment]
data(examplePathways)
data(exampleRanks)
 
RUN1:
fgseaRes <- fgsea(pathways = examplePathways, 
                  stats = exampleRanks,
                  minSize=15,
                  maxSize=500,
                  nperm=100000)

RUN2:
exampleRanks2<-reverse_ranking(exampleRanks) ## reverse gene order (reverse metric order so now pathways/NES = pathways/NES * -1)

fgseaRes <- fgsea(pathways = examplePathways, 
                  stats = exampleRanks2,
                  minSize=15,
                  maxSize=500,
                  nperm=100000)

Thanks

padj very similar between RUN1 versus RUN2 not exactly same but ES is identical for RUN1/RUN2 but signs are opposite. Can I run this so that the padj are identical, they should be in the ideal world.

Thanks

**Comment by davidlyon3** [comment]
Hi



I added some code example on github

https://github.com/ctlab/fgsea/issues/106


Thanks so much







On Tuesday, October 5, 2021, 04:03:43 AM EDT, Vladimir ***@***.***> wrote: 







Hi @davidlyon3 ,
could you please provide some code example?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vdsukhov** [comment]
@davidlyon3 
If I understood correctly, then `reverse_ranking` is the same as multiplying all gene-level statistics by -1. In this case, yes, the P-values will be slightly different, and this is due to the random number generator. In the case of multiplication by -1, the gene-level statistics are stored in reverse order inside of `fgsea`. This leads to minor differences in the estimation of P-values.
