### ISSUE TITLE
enrichment score seems to have inverse sign

### ISSUE THREAD

**Issue by EBosi** [ctlab/fgsea#108]
Edit: Nevermind, I re-ran fgsea and it solved the issue, you can close the issue
Hi,
thanks for maintaining this awesome tool. I have recently encounter this odd behavior, basically I found pathways expected to be down-regulated with a positive enrichment score and vice-versa. The GSEA plot confirmed my observation, in that pathways with positive ES have a negative enrichment pattern (the curve has a minimum in the bottom left) and vice-versa (curve has a maximum in the top left). Extracting the q-score values of the leading edge genes from the rank list returns mostly negative values for pathways with ES > 0 and positive ones for those with ES < 0.
What could be causing this issue? Let me know how/what can I share to further look into it.
Thanks!
Emanuele

**Comment by assaron** [comment]
Please, make a reproducible example for your problem, pointing out the particular things you were not expecting to get. Otherwise it's hard to answer your question.

**Comment by assaron** [comment]
Oh, saw the edit. Cool
