### ISSUE TITLE
Info on running multi-condition geseca

### ISSUE THREAD

**Issue by kvittingseerup** [ctlab/fgsea#109]
When running geseca (installed from [here](https://github.com/ctlab/fgsea/tree/geseca)) to do a multi-condition analysis (e.g. run on two differential expression analysis that I made) is the `E` argument to `geseca()` a matrix of `stats` similar to what I would input as `stats` in `fgseaMultilevel()` or is some post-procssing necessary (asking since it is highlighted the [vignette](https://github.com/ctlab/fgsea/blob/geseca/vignettes/geseca-tutorial.md) that expression values needs to be log-transformed).

**Comment by vdsukhov** [comment]
Hi! The `geseca` method is like an "unsupervised" method for performing an enrichment analysis. This means that you don't need to perform any manually curated differential expression analysis to run this method. The method simply a matrix of gene expressions (where values should be on a logarithmic scale, and quantile normalization should be performed for columns (samples)). So, `E` is just a slightly processed expression matrix (log-scale, quantile normalization as I already mentioned) and not a matrix that consists of statistics (e.g., moderated t-statistic) obtained after differential expression.

**Comment by kvittingseerup** [comment]
But could I use it to perform a joint enrichment analysis of e.g. two different datasets by providing a matrix of e.g. test statistics or would that be mis-using the tool?

**Comment by vdsukhov** [comment]
@kvittingseerup 
Actually, we designed `geseca` method for performing enrinchment analysis for gene expression matrices. So, we didn't consider the case where the method is run on a matrix where each column is a gene-level statistic (e.g. t-statistic or logFC). The main idea of the method is to skip the manual differential expression analysis and be able to work with matrices where there are a large number of different biological conditions (more than 2).

**Comment by assaron** [comment]
@kvittingseerup to add, GESECA's enrichment score captures correlation of genes in the gene set, more exactly the statistic is variance of the expression matrix projection on the genes from the gene set (see the slide below, where hypoxia pathway has hight enrichment score as the gene levels are highly correlated, but estrogene response pathway has low score).

So technically you can use it on t-statistics as well (or any other matrix), but we meant it to be used we normalized log-scaled gene expression values.

![geseca-score](https://user-images.githubusercontent.com/1040217/148779715-59b52b95-bd93-4122-982e-30284573b5e5.png)

**Comment by kvittingseerup** [comment]
Thanks for the thorough responses. And I really like the idea of using this on multi-condition datasets!

Guess the test-statistics approach could be used in cases where there are very uneven condition sizes or large batch effects :)
