### ISSUE TITLE
A weird result: Highly enrichement visually but p value is not significant

### ISSUE THREAD

**Issue by chent5** [ctlab/fgsea#114]
Hi,

Thanks a lot for developing this package. This package is very helpful and easy to use. Recently, I got a weird result as below figure:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/40006284/178886547-4f86af26-7b9a-43d6-ae03-c48ecccf82d2.png">

<img width="386" alt="image" src="https://user-images.githubusercontent.com/40006284/178886584-905762e4-843d-4f6e-935a-fd2326c0c397.png">

Visually, the turquoise geneset is highly enriched in the negative side of the ranked genes. However, p-value = 0.16, which doesn't make sense to me.

I tried ks test, the statistics are D = 0.8891, p-value < 2.2e-16. The p-value of the KS test is extremely significant.

Could you help to solve this issue?

Thank you so much!

**Comment by assaron** [comment]
It does look strange indeed. Can you upload the inputs (gene set and statistics vector) here, so that I can reproduce the behavior?

**Comment by chent5** [comment]
Thanks a lot for your quick response. Do you have a preferred email to receive the data?

**Comment by assaron** [comment]
You can send the data to alsergbox@gmail.com

**Comment by chent5** [comment]
I have sent the data to your email. Thank you so much for your help in advance!

**Comment by assaron** [comment]
Hi, sorry for the delay. I've checked your data, your `ranks` vector is highly unbalanced and skewed towards positive values, that's causing some troubles. There is an appropriate warning message if you use `fgseaMultilevel` and not the `fgseaSimple` version.

```
set.seed(123)
fgseaRes <- fgseaMultilevel(pathways = geneset, 
                  stats = rank,
                  minSize=15,
                  #  maxSize=500,
                  nPermSimple=100000
                  )
```

Give the following table:
```
     pathway  pval  padj log2err         ES       NES size
1: turquoise 1e-50 1e-50      NA -0.9566721 -4.031049  857
```

**Comment by chent5** [comment]
Thanks so much for your help!
