### ISSUE TITLE
is there a plan to implement fast ssGSEA?

### ISSUE THREAD

**Issue by Yunuuuu** [ctlab/fgsea#117]
We often use ssGSEA to calculate scores based on specific gene set, when we want to compare these different scores corresponding to different gene sets related to specific function, it's necessary to normalize these scores then compare them since the size of the underlying gene sets of these scores can give these scores different weight. Though the broadinstitute provide these function in https://github.com/broadinstitute/ssGSEA2.0, it's very slow and spend a lot of times to run a work.

Thanks to `fgsea`, we can run a lot of works easily and quickly, it would be great if `fgsea` can also run ssGSEA.

**Comment by assaron** [comment]
Did you try GSVA package? It has a relatively fast ssGSEA function implementation, but not sure how it compares with Broad's.

**Comment by Yunuuuu** [comment]
Thanks for your reply @assaron, `GSVA` do provide a fast ssGSEA but cannot caculate the NES (normalized enrichment scores), just like the regular GSEA. so we cannot compare different scores in a sample (For example: score based on gene set `Macrophage` vs score based on `Neutrophil`). We can only compare the specific scores related to a specific gene set (like score based on `Macrophage` gene set) between different samples.

**Comment by assaron** [comment]
Still I think it's probably better to ask @rcastelo for this feature to be added to `GSVA`. Our lab doesn't normally use ssGSEA, so we're unlikely to add such functionality to `fgsea` package.
