### ISSUE TITLE
Subset of genes

### ISSUE THREAD

**Issue by gjhuizing** [ctlab/fgsea#119]
Hello,

Let's say my `.rnk` file contains 2,500 genes and my `.gmt` file contains way more. Does `fgsea` take that into account by subsetting the gene sets to the input genes? Or do I need to manually subset the gene sets?

Thank you,

Geert

**Comment by assaron** [comment]
fgsea filters out all of the genes, not present in the ranking. You don't have to do it manually.

**Comment by gjhuizing** [comment]
Great, thank you for the quick reply!
