### ISSUE TITLE
getting different results from multiple fgsea runs (unstable)

### ISSUE THREAD

**Issue by Nelhachem** [ctlab/fgsea#12]
Dear Dr. Sergushichev,
Thanks for the great fast GSEA implementation in R.
I have issues when running fgsea multiple times (with same ranked list and settings).
I get slightly different results and this is kind of annoying for reproducibility concerns.
Is there a way to set the seed within the function? right now it is: seeds <- sample.int(10^9, length(permPerProc)) 
Would greatly appreciate your help
Best

**Comment by assaron** [comment]
Hi, 
Thank you for your report. Fgsea was designed to be compatible with set.seed() function. To make it reproducible just use it in the following way:
```
set.seed(42)
fgseaRes <- fgsea(examplePathways, exampleRanks, nperm=1000, maxSize=500, nproc=1)
```

For some reason it not always works when multiple threads are used, thus nproc=1.

**Comment by Nelhachem** [comment]
Thanks for your prompt reply
I have used before the set.seed() before running the fgsea function exactly as you mentionned 
However I still get slightly different results when running the same code twice on Rstudio or R in terminal

**Comment by assaron** [comment]
Is this happening even when you specify nproc=1?

**Comment by Nelhachem** [comment]
Exactly nproc = 1 this what I do

**Comment by assaron** [comment]
That's strange. Can you please run the following script, preferably by running `Rscript --vanilla` and paste here the outputs? Also, please paste `sessionInfo()` output.

```{r}
library(fgsea)
data("examplePathways")
data("exampleRanks")
set.seed(42)
print(sample.int(10^9, 1))
print(fgsea(examplePathways[1:2], exampleRanks, nperm=2000, maxSize=500, nproc=1)$nMoreExtreme)
print(sample.int(10^9, 1))
```

**Comment by Nelhachem** [comment]
Hi, If I run your code
library(fgsea)
data("examplePathways")
data("exampleRanks")
set.seed(42)
print(sample.int(10^9, 1))
xx <- fgsea(examplePathways[1:2], exampleRanks, nperm=2000, maxSize=500, nproc=1)
print(sample.int(10^9, 1))

and try to do it twice in my R console I get different results for pval, NES and padj...
look at the xx object

first run:
pathway      pval      padj         ES
1:               1221633_Meiotic_Synapsis **0.5566372** **0.8628629** 0.2885754
2: 1368092_Rora_activates_gene_expression 0.8628629 0.8628629 -0.3087414
          NES nMoreExtreme size              leadingEdge
1:  **0.9431694**          628   27  15270,12189,71846,19357
2: -0.6609324          861    5 20787,328572,12753,11865


second run:

 pathway      pval      padj         ES
1:               1221633_Meiotic_Synapsis **0.5569285** **0.8648374**  0.2885754
2: 1368092_Rora_activates_gene_expression 0.8648374 0.8648374 -0.3087414
          NES nMoreExtreme size              leadingEdge
1:  **0.9434315**          630   27  15270,12189,71846,19357
2: -0.6622885          850    5 20787,328572,12753,11865

**Comment by assaron** [comment]
Please, run the exact script I sent, `print(sample.int(10^9, 1))` before and after is important. Also,  `sessionInfo()` output would be helpful too.

**Comment by Nelhachem** [comment]
Ok I have run exactly your script:
library(fgsea)
data("examplePathways")
data("exampleRanks")
set.seed(42)
print(sample.int(10^9, 1))
[1] 914806044
print(fgsea(examplePathways[1:2], exampleRanks, nperm=2000, maxSize=500, nproc=1)$nMoreExtreme)
[1] 630 850
print(sample.int(10^9, 1))
[1] 830447627

When I run it again, I get same results but not in the object when you look in the table

sessionInfo() 
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fgsea_1.0.2  Rcpp_0.12.13

loaded via a namespace (and not attached):
 [1] grid_3.3.3          plyr_1.8.4          gtable_0.2.0       
 [4] scales_0.5.0        ggplot2_2.2.1       rlang_0.1.4        
 [7] lazyeval_0.2.1      data.table_1.10.4-3 fastmatch_1.1-0    
[10] BiocParallel_1.8.2  tools_3.3.3         munsell_0.4.3      
[13] parallel_3.3.3      colorspace_1.3-2    gridExtra_2.3      
[16] tibble_1.3.4

**Comment by assaron** [comment]
I've changed the code a little bit which eliminated one of the places which affected sampling reproducibility. Please, install the last version from github using `devtools::install_github("ctlab/fgsea")` command and check if it got better for you.

**Comment by Nelhachem** [comment]
Thanks! I will try the new code and get back to you

**Comment by assaron** [comment]
Actually the fix doesn't work for both OS X and Windows. It only works fine on Linux. I'm closing the issue in favor of #13

**Comment by Nelhachem** [comment]
Ok thanks, hope you find a way to fix the issue on both OS X and Windows.
I run the fix you send me on OS X Sierra with R version 3.4.3 (2017-11-30) and it seems the results are consistent between different runs

**Comment by Nelhachem** [comment]
Sorry again!, I get same inconsistency as before. Good luck
Awaiting your fix for Mac OSX

**Comment by assaron** [comment]
Hi, I found and fixed the error. Please try the latest version.

**Comment by Nelhachem** [comment]
Thanks, I'll do

**Comment by pforny** [comment]
@assaron thanks for the fantastic fgsea package. but i keep running into the same issue as described above. i set the seed with the set.seed function and regardless of the nproc variable i keep getting slightly different results. i also use the most recent version with R 4.1.0 on mac big sur. thanks for your help!
