### ISSUE TITLE
Question: about scoreType = 'pos'

### ISSUE THREAD

**Issue by noblegasss** [ctlab/fgsea#123]
Hello there! First of all, thanks for implementing the pre-ranked gsea algorithm in R, which is really helpful.
I'm using the package for my current project and there are several questions that I encountered. 

```
c2.cp.fgsea <- fgsea(
  pathways = c2.cp.list, 
  stats    = rank,
  minSize  = 15,
  maxSize  = 1000,
  scoreType = 'pos'
)
```

1. When one specifies score type = "pos", is it mandatory that all the values of "stats" need to be positive? Would negative values for "stats" be permitted by the algorithm?
2. What would be the hypothesis when score type = "pos"? Is the hypothesis that the genes in a gene set are enriched with genes having larger values of the statistic specified in "stats"?

Thank you so much for your help!

**Comment by assaron** [comment]
Hi,

1. Not, `scoreType="pos"` doesn't require for the input stats vector to be positive.
2. Classic pre-ranked GSEA is a two-tailed test: both positive and negative enrichment are of interest. In case `scoreType="pos"` or  `scoreType="neg"` only positive or negative enrichment is considered respectively, in other words only the upper or lower part of the enrichment curve. In both of the cases the test is one-tailed: we calculate the probability of a random pathway to have enrichment score as high as score for the input pathway.
