### ISSUE TITLE
GESECA function not existing

### ISSUE THREAD

**Issue by DirtyHarry80** [ctlab/fgsea#125]
I am trying to replicate your work on spatial transcriptomics data, however in your script you are using a function "geseca" which does not exist in any of the libraries you load in your script. So where the heck does this function come from?

**Comment by DirtyHarry80** [comment]
Sorry but when I do that R automatically pulls the version 1.12.0. My R version is 3.6.3, so it should be ok. Installing from Github is also impossible:
> library(devtools)
Loading required package: usethis
Error in get(genname, envir = envir) : object 'testthat_print' not found
> install_github("fgsea")
Error in parse_repo_spec(repo) : Invalid git repo specification: 'fgsea'

**Comment by DirtyHarry80** [comment]
Thank you that worked well but from GitHub (not from Bioconductor, which kept installing the old versions).

**Comment by assaron** [comment]
You need an R>=4.2 to be able to upgrade to the latest Bioconductor release.
