### ISSUE TITLE
Spatial Code Error in base::colSums

### ISSUE THREAD

**Issue by DirtyHarry80** [ctlab/fgsea#126]
Hi, I am trying to apply your code (copy paste) on the spatial data but with no success for the moment. I had trouble to find a clean vignette describing what needs to be done. So I found one deposited here (in "geseca-tutorial.Rmd")....but it does not work..several syntax problems exist in the code in addition:   |>  (what is this representing in the code?) then this ![] .... ?

-----
topPathways <- gesecaRes[, pathway] |> head(4)
for (ppn in topPathways) {
    pp <- pathways[[ppn]]
    pp <- intersect(pp, rownames(E))
    
    score <- colSums(brain@assays$SCT@scale.data[pp, ])/sqrt(length(pp))
    brain@meta.data[[ppn]] <- score
}
SpatialFeaturePlot(brain, features = topPathways, )
```

![](geseca-spatial-top.png){width=100%}

-----

1st error just after " brain@meta.data[[.....
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

**Comment by assaron** [comment]
`|>` is a pipe operator introduced in R 4.1. If you have earlier versions you can try to replace it with the operator `%>%` which can be imported from `magrittr` package. But I do recommend updating to the recent R version.

`![] ..` is not part of the code meant to be executed, please follow the compiled vignette, not the raw Rmd file, there it's more clear where is the code part, and how the plots should look like: https://bioconductor.org/packages/release/bioc/vignettes/fgsea/inst/doc/geseca-tutorial.html

**Comment by DirtyHarry80** [comment]
Thank you, indeed, sorry for my ignorance.

**Comment by Pedramto89** [comment]
Hi @assaron 


I have several samples stored in the seurat object, resulted from a spatial transcriptomics analysis. When I want to do the analysis via 'plotCoregulationProfileSpatial' function, I only see the results for one the samples while I have three samples. 
How can I specify the sample for the analysis?
Best

**Comment by assaron** [comment]
@Pedramto89 it's a good question, I think it's actually not really possible at the moment. Let me create a separate issue for that.

As a workaround you can split the sample into separate objects and do the plotting that way.

**Comment by Pedramto89** [comment]
Thank you @assaron for your quick response!

I tried to subset the seurat obj to have a specific level of data for the slice of interest, but it did not work and could not visualize the result.
