### ISSUE TITLE
Which genes should I use?

### ISSUE THREAD

**Issue by dekan-aleksandr** [ctlab/fgsea#131]
Hello, fgsea developers!
I am confused about the genes I should use in fgsea. Could you please clarify the following?

1) fgsea does not require a background set of genes. As I understand, it extracts the background genes from the sorted input vector. Is this correct?
2) I use Log FC for sorting genes and I include all genes present in my dataset. The problem here is that low-expressed genes are likely to have huge Log FC, but are not statistically significant. Ranking genes using LogFC does not seem valid. What should I do?
3) If I am interested only in upregulated pathways, should I input only positive logFC?

**Comment by assaron** [comment]
Hi,

1) Yes, the background are all of the genes from the input vector.

2) Ranking genes by logFC is technically correct, but we usually rank genes by the differential expression test statistic (`t` column from `limma` and `stat` column from `DESeq2`. However, we recommend to keep only the properly expressed genes, something like top 12000 genes by the average expression (for bulk transcriptomics data). 

3) No, it's better to keep both positive and negative genes in any case, but you can run a one-tailed test, specifying `scoreType="pos"` option to look only for upregulation.

**Comment by dekan-aleksandr** [comment]
Thank you! Great!

In the second point, you say that it is better to keep properly expressed genes. 
It means that there is an error in the most popular answer in #50. 

@konsolerr finds all, even not properly expressed genes, by setting min.pct = 0 and not taking only reasonably expressed genes. It means that extremely low expressed genes are retained as well. 

How much should a gene be expressed to include it in the analysis? The top 12000 genes seem to be very species and sample dependent.

Thank you
