### ISSUE TITLE
Question: distribution requirements of statistics

### ISSUE THREAD

**Issue by kvittingseerup** [ctlab/fgsea#134]
Do you have any suggested distribution requirements or suggestions for the statistics given to the `stats` argument of `fgsea::fgseaMultilevel()` ?

I've been using `-log10(p-values)` and was wondering if a few extreme p-values could be given to much weight. Hence the question 🙂

Cheers
Kristoffer

**Comment by ToledoEM** [comment]
This is a nice read @kvittingseerup https://www.gsea-msigdb.org/gsea/doc/GSEAUserGuideFrame.html 
Personally Signal2Noise and logFC has always been good metrics in my experiments

**Comment by kvittingseerup** [comment]
Thanks for the quick answer
