### ISSUE TITLE
How to report for enriched gene sets?

### ISSUE THREAD

**Issue by Close-your-eyes** [ctlab/fgsea#140]
Dear all,

this is not a technical question but rather one related to scientific or statistical conduct.

I am testing all gene sets (or pathways) from MsigDB for enrichment in a pre-ranked gene list. Many gene sets are significantly enriched (i.e. adj p value is below a certain threshold). Some of those fit my narrative but some do not. Others are completely out-of-context with respect to the cells that were basis to generating the pre-ranked gene list. Those gene sets that fit my narrative do not have the lowest p-values though. Other out-of-context gene sets occupy the lowest p-values. Some of the gene sets that fit my narrative are related (e.g. they all deal with transport of ions across the cell membrane or whatever) and their p-values are somewhat uniformly distributed from 0.05 to 1.4e-10 (which the lowest p-value achieved by any of the gene sets tested; just an example).

How should I report for those gene sets that fit my narrative? The problem I see is cherry picking. If I only report for what suits my story but leave out all the rest is not objective. On the other hand, it is not pure coincidence that these gene sets that fit my narrative got assigned with a significant enrichment - they fit the context.

**Comment by assaron** [comment]
Hi @Close-your-eyes 

Pathway enrichment is usually should not be the end result of the analysis: it's not a direct or sufficient evidence of any biological activity, but should be considered as a means to get some insights into what's going on and help generate you hypotheses to validate by alternative (preferably experimental) approaches. 

Given that, I think it's OK to follow-up on some particular pathway that you find more promising to test, for example when you can test its relevance experimentally. However, if there is no "follow-up", it could help to somehow group the pathways and highlight some particular ones that have some additional evidence, e.g. to say the top pathways are cell-cycle and ion transport related but also involvement of ion transport is supported by this and that studies.

**Comment by Close-your-eyes** [comment]
Thanks for your reply of course!
