### ISSUE TITLE
Question: scaling size of spots

### ISSUE THREAD

**Issue by jyoo19** [ctlab/fgsea#146]
Hello, 

I am using plotCoregulationProfileSpatial() for our Visium data and was wondering if there is any option for scaling the size of the spots.

Thank you!

**Comment by assaron** [comment]
Hi @jyoo19. Currently there is no such option. As a workaround you can look at plotCoregulationProfileSpatial code and just make your own function. Specifically, the most important bit is using `fgsea:::addGesecaScores` function to calculate scores and add them to Seurat object. Something along these lines:

```
myPlotCoregulationProfileSpatial <- function(pathways, object, assay = DefaultAssay(object), prefix = "", 
    scale = FALSE) {
    obj2 <- fgsea:::addGesecaScores(list(pathway = pathway), object, 
        assay = assay, scale = TRUE)
    p <- Seurat::SpatialFeaturePlot(obj2, features = "pathway", 
        combine = FALSE, image.alpha = 0)[[1]] # you can modify options here
    p$scales$scales[p$scales$find("fill")] <- NULL
    suppressMessages({
        p2 <- p + scale_fill_gradientn(limits = c(-3, 3), breaks = c(-3, 
            0, 3), oob = scales::squish, colors = colors, guide = guide, 
            name = "z-score") + theme(legend.position = theme_get()$legend.position)
    })
    if (!is.null(title)) {
        p2 <- p2 + ggtitle(title)
    }
    p2
 }
 ```

**Comment by jyoo19** [comment]
Thank you for your quick response! It was very helpful :)
