### ISSUE TITLE
Try to understand how ES is calculated

### ISSUE THREAD

**Issue by ghbore** [ctlab/fgsea#147]
Hi! I was trying to understand how GSEA score is calculated, but I'm having trouble wrapping my head around two parts. Hope to get some guidance here.

1. Why are the maximum positive and negative deviations calculated from two different curves?

    Inside the [fgsea.R/calcGseaStat function](https://github.com/ctlab/fgsea/blob/ecfb89c55d938ca84605f1a1380a8cedd70f1ccf/R/fgsea.R#L122), 
    ```R
        tops <- rCumSum - (S - seq_along(S)) / (N - m)
        if (NR == 0) {
            # this is equivalent to rAdj being rep(eps, m)
            bottoms <- tops - 1 / m
        } else {
            bottoms <- tops - rAdj / NR
        }
    
        maxP <- max(tops)
        minP <- min(bottoms)
    ```
    `tops` and `bottoms` are different. I hardly get it.

2. Why ES will be zero when the positive and negative deviations are equal? But they are less likely equal in R.

    ```R
        switch(scoreType,
               std = geneSetStatistic <- ifelse(maxP == -minP, 0, ifelse(maxP > -minP, maxP, minP)),
               pos = geneSetStatistic <- maxP,
               neg = geneSetStatistic <- minP)
    ```
    
    I played this function with an example:
    ```R
    library(fgsea)

    stats <- setNames(
        c(
            3.3, 3.2, 3.1, 
            3, # hitted d
            2.2, 2.1,
            2, 0, -2, # hitted g, h, i
            -2.1, -2.2, 
            -3, # hitted l
            -3.1, -3.2, -3.3
        ),
        letters[1:15]
    )
    
    pathways <- list(
        "manual" = c("d", "g", "h", "i", "l")
    )
    
    scoreTypes <- c("std", "pos", "neg")

    setNames(scoreTypes, scoreTypes) |>
        lapply(function (s){
            fgsea:::calcGseaStat(
                stats,
                na.omit(match(pathways[[1]],names(stats))),
                scoreType = s
            )
        })
    ```
    It turned out:
   ```R
    $std
    [1] 0.3
    
    $pos
    [1] 0.3
    
    $neg
    [1] -0.3
   ```
   Though the `maxP` and `-minP` are theoretically equal, the `==` expression is rarely `True` in R, and ES is still 0.3 when `scoreType` = "std". Not sure if this is expected behavior.

Thanks in advance!

**Comment by assaron** [comment]
@ghbore sorry for not replying earlier. Both `tops` and `bottoms` are points on the same enrichment curve, as you figured out correctly. It is guranteed that the minimum is reached just before some gene in the gene set, and the maximum is just after some gene.

Also, as you noted, ES is practically never zero. This case is just for symmetry of the technical definition.

**Comment by ghbore** [comment]
No worries at all. Thank you very much, @assaron, for your patient explanation and taking the time to help me understand them better.
