### ISSUE TITLE
are there p-value calculated for each leading edge gene?

### ISSUE THREAD

**Issue by Leran10** [ctlab/fgsea#148]
Hi,

I used fgsea to calculate enrichment. I want to know if each leading edge gene also has a p-value or adjust p-value that I can fetch and make plot with it?

Thanks!
Leran

**Comment by assaron** [comment]
Not sure what you mean. All of the genes usually have differential expression p-values, which is normally done before GSEA. FGSEA doesn't add any additional gene-level p-values, only pathway-level.

**Comment by Leran10** [comment]
Thanks for your reply! that's what I thought just want to confirm!
