### ISSUE TITLE
How to prepare pathway used for fgsea function

### ISSUE THREAD

**Issue by yulchen810** [ctlab/fgsea#159]
Hi,
I note that you provide a table containing pathway, pval, etc. I'm wondering how to prepare or create that data, does that come from DEGs or other data?

Thank you!

**Comment by yulchen810** [comment]
> I'm not sure I got your question, can you be more specific? There are a number of vignettes showing how to use fgsea:
> 
> * https://bioconductor.org/packages/release/bioc/vignettes/fgsea/inst/doc/fgsea-tutorial.html
> * https://davetang.org/muse/2018/01/10/using-fast-preranked-gene-set-enrichment-analysis-fgsea-package/
> * https://stephenturner.github.io/deseq-to-fgsea/
> 
> You can also check out `clusterProfiler` package which wraps fgsea and makes some of the functionality simpler.

I have snRNA-seq data and want to apply gsea analysis to it. [Here](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Using_RNA-seq_Datasets_with_GSEA) mentioned the data should be normalized gene counts after filtering low-quality cells. But it seems that differential expression genes(DEGs) produced by FindMarkers function can also be used to do GSEA analysis. 
So I'm not sure which one is better, all genes or just DEGs of different conditions?
Best

**Comment by assaron** [comment]
First of all, for GSEA you should always use all of the (expressed) genes, never filter it by differential expression. 

That said, there are two types of GSEA analysis: sample- and gene- permuting (also called preranked). The first one takes the whole table of gene expression and the second takes differential gene expression table (but not filtered by p-value). Currently, the most common is the second option. In my personal opinion, the first one never works (although the second one also has some issues).

Alternatively, you can consider running GESECA analysis method, that takes the whole gene expression matrix (including single cell data). You can check out the vignette here: https://bioconductor.org/packages/release/bioc/vignettes/fgsea/inst/doc/geseca-tutorial.html

**Comment by assaron** [comment]
@yulchen810 Also, for more general questions, I'd suggest to use biostars.org platform. It has big community, so there is a bigger chance that someone will be able to help you.

**Comment by yulchen810** [comment]
> @yulchen810 Also, for more general questions, I'd suggest to use biostars.org platform. It has big community, so there is a bigger chance that someone will be able to help you.

Thank you!
