### ISSUE TITLE
Parallel backend running out of resources

### ISSUE THREAD

**Issue by topherconley** [ctlab/fgsea#16]
Hi, 

First, very nice package. 

If I run `fgsea` hundreds or thousands of times by means of an `lapply` or `foreach::foreach`, either on linux or Mac, it generates a lot of zombie processes and then runs out of resources. It would be nice to turn off the `BPPARAM` or `nproc` option and run serially. Even better, I can then wrap this inside a solid and stable backend like `doParallel` combined with an iterator like `foreach` and not have to deal with an unsatisfactory `BiocParallel` wrapper. 

Why I am running this hundreds or thousands of times has to do with a specific application not (historically) common in bioinformatics data sets. 

Thanks in advance, 
Chris

**Comment by assaron** [comment]
Hi Chris,

I've asked this question on Bioconductor support site: https://support.bioconductor.org/p/104702/

In the meantime, you can set `nproc` option to `1`. This shouldn't create additional processes.

Best,
Alexey

**Comment by assaron** [comment]
As Martin Morgan said on the Bioconductor Support, this issue is fixed in R-devel version. You can try to install it from source or wait for the release.
