### ISSUE TITLE
Understandig GESECA results 

### ISSUE THREAD

**Issue by Teulip** [ctlab/fgsea#161]
Hi,

I am using GESECA for my spatial transcriptomic data analysis and am interested in determining which pathways are upregulated and which are downregulated based on the results. Is there a way to identify upregulated and downregulated pathways from the GESECA output?

Any help on this matter would be greatly appreciated.

Thank you!

**Comment by vdsukhov** [comment]
Hi @Teulip,

You might want to try using the `plotCoregulationProfileSpatial` function to visualize the top significant pathways from your GESECA analysis if you have results from Visium spatial transcriptomics. This function highlights regions of the tissue that show high expression of the gene set, making it easier to interpret your findings.

Let me know if you need any further assistance!

**Comment by Teulip** [comment]
Hi @vdsukhov,
Thank you so much for the suggestion! Using the plotCoregulationProfileSpatial function to visualize the top significant pathways makes sense now, and I think it will really help with interpreting my GESECA results. I appreciate your help and will reach out if I need any further assistance. Thanks again!
