### ISSUE TITLE
Installation issue:warning: "Boost.Math requires C++14" 

### ISSUE THREAD

**Issue by ciel1021** [ctlab/fgsea#165]
I am trying to download the fgsea on MacOS using binary file. I got this error when I just to install.
warning: "Boost.Math requires C++14" [-W#warnings]
I check the DESCRIPTION file it states that it requires C++11 system.
I just want to double check if I should use C++14 or C++11, if using C++14, is there any part of the script I need to modify?
Below is the screenshot of the error message.
Thank you so much for your help
 
![Screenshot 2024-12-18 at 6 16 50 PM](https://github.com/user-attachments/assets/f8360bb1-19ad-4e91-8def-ab49a772cfad)

**Comment by bbimber** [comment]
This might be related to something our CI just picked up. fgsea installation is failing for us in a docker image. I believe the change is the latest BH package release: https://github.com/eddelbuettel/bh. Building fgsea worked with BH 1.84.0-0, but not 1.87.0-0

**Comment by TANGLi83-star** [comment]
Same problem here, does anyone know how to solve it?

**Comment by TANGLi83-star** [comment]
OK, I just solved the problem by isntalling the BH 1.84.0-0, and then successfully installed the fgsea package, thanks bbimber!

**Comment by chaimol** [comment]
run as follow in R, it successful runing:
```
package_url <- "https://cran.r-project.org/src/contrib/Archive/BH/BH_1.84.0-0.tar.gz"
utils::install.packages(pkgs = package_url, repos = NULL)
BiocManager::install("fgsea")
```

**Comment by bbimber** [comment]
Yes, remotes::install_version('BH', '1.84.0-0') will probably also do it. 

If any of the tool developers are monitoring these, is this issue something you will be able to address for BH 1.87.0-0? Or is this a matter of CRAN binaries needing to be updated or something that will happen given time?

**Comment by ciel1021** [comment]
> This should be fixed in the master branch. `remotes::install_github("ctlab/fgsea")` should finish correctly now, even with the newes `BH` version.

I am afraid I still have some issue. When I try to do remotes install.
<img width="586" alt="Screenshot 2024-12-22 at 2 18 11 PM" src="https://github.com/user-attachments/assets/ce9c1ba4-e7e1-43d5-a0b0-7d5219ea90ad" />

**Comment by assaron** [comment]
@ciel1021 your problem does not seem to be related. Run the suggested command `pkgbuild::check_build_tools(debug = TRUE)`, probably it will give your more details. Probably you don't have `gcc` compiler installed, or something along the lines.
