### ISSUE TITLE
Change size of vertical lines

### ISSUE THREAD

**Issue by jchellmuth** [ctlab/fgsea#17]
I am using fgsea with a larger dataset than usual and a high percentage of the rank overlaps with the pathway. This causes the vertical lines in the indicator bar to appear as a continuous black block. I have two inconvenient workarounds (subsampling the dataset and chaning the width of the plot) but, ideally I would like to change the size of the individual vertical lines to prevent them form melting together. Is there a way to change the size of the vertical line ?
[plot_Gsea_OCAB.pdf](https://github.com/ctlab/fgsea/files/1692161/plot_Gsea_OCAB.pdf)

**Comment by assaron** [comment]
Hi, I'm not sure the barcode plot is suitable for such big gene sets, so won't be adding an option for this in the code at the moment.

However, you can change it manually and play around pretty easily:
```{r}
p <- plotEnrichment(examplePathways[["5991130_Programmed_Cell_Death"]],
               exampleRanks)
p$layers[[6]]$aes_params$size <- 0.05
print(p)
```

This will replace line size with 0.05 instead of default 0.2.
