### ISSUE TITLE
Bug when no genes pass the min/max size threshold

### ISSUE THREAD

**Issue by nachocab** [ctlab/fgsea#2]
Great job on the tool!

I spotted a bug here: https://github.com/ctlab/fgsea/blob/master/R/fgsea.R#L140

If `pathwaysFiltered` is an empty vector `numeric(0)` (because no genes passed the min/max thresholds) calling `sapply(pathwaysFiltered, length)` on it will return a `list()` (one of R's kinks), which means that the next line will be `max(list())`, which will give an error. You can get around this by checking to see if `length(pathwaysSizes) > 0` .

**Comment by assaron** [comment]
Thanks for the report! It should be fixed now.

**Comment by nachocab** [comment]
Awesome, thanks Alexey
