### ISSUE TITLE
No Significant pvalue_adjusted

### ISSUE THREAD

**Issue by tiagobrc** [ctlab/fgsea#23]
Hi, Thanks for creating this awesome package. 

I have a doubt, I have been trying to do fgsea in R using pre-ranked based on log2fold change values. I notice that fgsea do the sorting from the highest positive to lowest negative.  I tried several times with several datasets but never got a single significant (fdr < 0.01) pathway in several genesets. I thought this was very strange and did a faked pre-ranked file with all Glycolysis set from kegg in the edge of the list to get a super high enrichment score (Fig1). Even then, no significance was reported by fgsea. A low enriched pathway got more significance than the Glycolysis (Fig2). Can you point me to what I could be doing wrong?

I have attached the R objects that I am using. (pathway_rank_R_iamges.zip) 
![screenshot 2018-08-01 22 07 01](https://user-images.githubusercontent.com/12516337/43558387-3cf15e44-95d7-11e8-9076-946328854c27.png)

Thank you.

Fig1

![rplot01](https://user-images.githubusercontent.com/12516337/43558302-c53bcec0-95d6-11e8-9f8b-bf773991b2e9.png)

Fig2
![rplot](https://user-images.githubusercontent.com/12516337/43558181-29f4b81e-95d6-11e8-817b-2b7ecb410f98.png)

[pathway_rank_R_iamges.zip](https://github.com/ctlab/fgsea/files/2251792/pathway_rank_R_iamges.zip)

**Comment by assaron** [comment]
What `nperm` value are you using? It looks like you are using nperm=100. This this to low for an actual analysis, values >= 10000 should be used.

**Comment by tiagobrc** [comment]
I used 1000, I will try with higher values.

**Comment by assaron** [comment]
Great, I'm closing the issue then.
