### ISSUE TITLE
Error in plotEnrichment() when input contains NA values.

### ISSUE THREAD

**Issue by bdemarest** [ctlab/fgsea#24]
I found that this error occurs when the input named vector of scores contain NA values.

```
plotEnrichment(zebrafish_GO[["extracellular_matrix(2)"]], ranked_vec)
Error in if (NR == 0) { : missing value where TRUE/FALSE needed
traceback()
2: calcGseaStat(statsAdj, selectedStats = pathway, returnAllExtremes = TRUE)
1: plotEnrichment(zebrafish_GO[["extracellular_matrix(2)"]], ranked_vec)

```

It might be nice to check for NAs in the input and give a more informative error.

By the way, fgsea() does not give an error given the same  NA-containing input.

**Comment by assaron** [comment]
fixed by https://github.com/ctlab/fgsea/commit/7f9ac2844bb88762728a78534e195ebe26c73ecd
