### ISSUE TITLE
Plot modifications

### ISSUE THREAD

**Issue by obruck** [ctlab/fgsea#29]
Hi! Would it be possible to add arguments to modify plots? Especially the output of the function plotGseaTable is a bit limited and changing fonts and colors of signaling pathways and bars could be nice. Maybe that would be possible by altering the source code, but was not able to do that.

Nonetheless, this is a very nice and efficient package!

**Comment by obruck** [comment]
Nice to hear! It could follow either ggplot guidelines or general plotting guidelines. One very simple example could be
```
plotGseaTable <- function(pathways, stats, fgseaRes,
                          gseaParam=1,
                          colwidths=c(5, 3, 0.8, 1.2, 1.2),
                          family="sans",
                          fontface="plain",
                          size = 1)
```
I can't think why somebody would like to have different font for the pathway name and p-values but maybe keeping it possible to alter each separately might be useful for somebodh nice.

**Comment by obruck** [comment]
Nice to hear! It could follow either ggplot guidelines or general plotting guidelines. One very simple example could be
```
plotGseaTable <- function(pathways, stats, fgseaRes,
                          gseaParam=1,
                          colwidths=c(5, 3, 0.8, 1.2, 1.2),
                          family="sans",
                          fontface="plain",
                          size = 1)
```

**Comment by assaron** [comment]
@obruck it took awhile, but now (experimentally) `plotGseaTable` text elements can be controlled:

```
data("examplePathways")
data("exampleRanks")
fgseaRes <- fgsea(examplePathways, exampleRanks, minSize=15, maxSize=500)
topPathways <- fgseaRes[head(order(pval), n=15)][order(NES), pathway]
p <- plotGseaTable(examplePathways[topPathways], exampleRanks,
              fgseaRes, gseaParam=0.5, 
              pathwayLabelStyle=list(size=10),
              headerLabelStyle = list(color="red",  family="Sans Serif"), 
              valueStyle = list(size=10),
              axisLabelStyle = list(size=6))

p
ggsave(p, width=10, height=8, file="table.png")
```

![table](https://user-images.githubusercontent.com/1040217/188106288-5c775de8-62ab-4280-a116-6ab98b9c7bed.png)

**Comment by obruck** [comment]
Sounds great! Thanks!
