### ISSUE TITLE
Warning about recycled values

### ISSUE THREAD

**Issue by renozao** [ctlab/fgsea#3]
Hi, 

I am getting this warning when running `fgsea` on reactome pathways obtained from the package's `reactomePathways` function, using my top 100 genes:

```
Warning messages:
1: In `[.data.table`(pvals, , `:=`(leadingEdge, list(leadingEdges))) :
  Supplied 192 items to be assigned to 745 items of column 'leadingEdge' (recycled leaving remainder of 169 items)
```
The returned value contains many NAs in place of the pathways.
Will try to narrow this issue down, but maybe you can check if there is no `cbind` operation that would lead to this.

**Comment by assaron** [comment]
Hi,

Could you paste list of genes that you're checking?

**Comment by assaron** [comment]
@renozao Unfortunately, I can't replicate this error. Can you, please, provide more information?

**Comment by renozao** [comment]
Well... I tried and I could not reproduce it either!!!
Not sure what was the cause of the error. Maybe I had `NA` values in my inputs.
Problem solved :)

**Comment by assaron** [comment]
Great it worked out, but I'm still wondering what have happened.
