### ISSUE TITLE
Better - opensource licence ?

### ISSUE THREAD

**Issue by serine** [ctlab/fgsea#32]
@assaron thanks for the package, starting to explore it now. I have a couple of questions, but i'll keep em as separate issues.

The licence for this repo aren't very permissive, from what I understand reading a bit [here](https://searchsecurity.techtarget.com/definition/copyright) and [here](https://choosealicense.com/no-permission/) I can't take a fork of the repo and/or modify the source in any way. I'm not sure if this is what you've intended. It would be great if you could update your licence to be more opensource like. Quoting from one of the article I've mentioned above

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

Also, this isn't directly related to this repo but shiny app https://github.com/ctlab/fgsea-web which you also contribute to, doesn't have a licence at all, would be great if you could add opensource licence to that repo too

[This is pretty good site that helped me to pick a licence](https://choosealicense.com/). 

cheers

**Comment by assaron** [comment]
Hi, the licence is MIT, as was stated in the DESCRIPTION file: https://github.com/ctlab/fgsea/blob/master/DESCRIPTION#L37 I also updated the LICENCE file for it to be more clear.
