### ISSUE TITLE
Loading own data

### ISSUE THREAD

**Issue by PaulineMarangoni** [ctlab/fgsea#37]
Hi there,

I have been trying to explore your vignette and now wanted to try applying the same workflow to my own pre-ranked files. However, I keep getting the same error reported regarding my rnk file

`> rnk.file <- system.file("extdata", "Cluster11_GSEA.rnk", package="fgsea")`
`> ranks <- read.table(rnk.file, header = TRUE, colClasses = c("character", "numeric"))`
Error in read.table(rnk.file, header = TRUE, colClasses = c("character",  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

I not sure the rnk file was formatted properly, but also not sure about calling the functions exactly how I am supposed to. Any help you could provide on this matter would be highly appreciated.

Thanks!

**Comment by assaron** [comment]
`rnk.file` should the full path to the file with ranks, `"Cluster11_GSEA.rnk"`. Don't use system.file call,  it is just to get the example file coming with the package.

```
rnk,file <- "Cluster11_GSEA.rnk"
ranks <- read.table(rnk.file, header = TRUE, colClasses = c("character", "numeric"))
```

**Comment by PaulineMarangoni** [comment]
Great, it seems that I can move forward now! Thanks again for your speedy reply!

**Comment by pstew** [comment]
Thanks, had the same issue!
