### ISSUE TITLE
plotGseaTable saveable to a variable like plotEnrichment

### ISSUE THREAD

**Issue by chrismiddleton** [ctlab/fgsea#42]
I have a Shiny app that I'm trying to use to display multiple plots. I encountered a problem where the result of plotGseaTable gets displayed in the RStudio viewer window instead of in the browser with the rest of my page. I've found that plotEnrichment has no issue like this, but plotGseaTable does.

Here is a minimum not-working example:

    library(dplyr)
    library(fgsea)
    library(ggplot2)
    gseaResult <- fgsea(pathways = examplePathways, stats = exampleRanks, nperm = 10)
    topPathways <- gseaResult[NES > 0][head(order(desc(NES)), n = 10), pathway]
    gseaPlot <- plotGseaTable(examplePathways[topPathways], exampleRanks, gseaResult)

Even though it's been stored in a variable, it shows up in the RStudio plot window. In the context of my Shiny app, this causes it to show up in the plot panel and not in the browser.

Whereas if you try:

    gseaEnrichment <- plotEnrichment(examplePathways[[topPathwayUp]], exampleRanks)

it doesn't show up in the plot window.

See this SO question for a larger example of how it's not working for me:

https://stackoverflow.com/questions/55421131/shiny-plot-shows-up-in-rstudio-window-instead-of-in-browser

A colleague could not reproduce the issue and they have version 1.6 of fgsea, whereas I've seen the problem with 1.8 (Bioconductor) and 1.95 (Github).

**Comment by chrismiddleton** [comment]
I just downgraded from version 1.8 to 1.6 to test, but it still shows up in the RStudio plot window.

**Comment by assaron** [comment]
plotGseaTable was not designed to be saveable to a variable, unlike plotEnrichment. As a workaround you can create file-based device with `png()`, `svg()` or `pdf()` calls.

**Comment by chrismiddleton** [comment]
@assaron Thanks, that clarified a lot. I made a PR to add an optional parameter that would allow saving to a variable, but default to the current behavior here: https://github.com/ctlab/fgsea/pull/43

**Comment by assaron** [comment]
Thanks, I've merged the PR.

**Comment by ahdee** [comment]
alternatively you could use: ```p2 <- recordPlot()``` this will save the output plot as an object; although if you want to combine with other ggplots as with patchwork you may need to convert it first.

**Comment by assaron** [comment]
@ahdee not sure what you mean: starting from version 1.23.1 `plotGseaTable` returns `ggplot` object, so it can be combined with other plots as well

**Comment by ahdee** [comment]
@assaron ah sorry - I must be using an older version. btw - awesome and very useful package - use it often.
