### ISSUE TITLE
Standard errors for Normal enrichment score

### ISSUE THREAD

**Issue by saksham219** [ctlab/fgsea#44]
Hi
I was wondering if we can obtain standard errors for the normal enrichment scores. If I assume correctly, the p value is being calculated by bootstrapping. A similar method can be implemented to find random normal enrichment scores and take their standard deviation to include as the standard error.

**Comment by assaron** [comment]
Could you clarify, why are interested in this? It can be implemented, but don't think it would be useful.

**Comment by saksham219** [comment]
An example where this could be helpful is a plot like this. Publication figures often include error bars, and if GSEA is done for multiple pathways at multiple conditions(time points, for instance) something like this may be useful.
![example_plot](https://user-images.githubusercontent.com/28567402/56082370-cd2bfb00-5e35-11e9-8912-9d9e0b9623ab.png)

**Comment by assaron** [comment]
Got it. There are two types of errors for normalized enrichment scores. One is technical: the NES is defined as an Enrichment Score (a fixed value for the given vector of weights and a pathway) divided by an expected value of ES for a random gene set of the same size (approximated as an average of generated samples). The technical error in calculating the expected ES and NES is quite small: around 0.01 for runs with nperm=10000, and gets even smaller with an increase of nperm.  The other error is biological: what NES would be if we repeat the experiment with the same design. This is the error that is meaningful to plot, but it can't be calculated in the current framework.

**Comment by assaron** [comment]
Actually, I think it's incorrect to compare NES values between rankings. You could try to look at average log-fold change instead, this would be more meaningful and correct.
