### ISSUE TITLE
scoring scheme

### ISSUE THREAD

**Issue by stefanCoH** [ctlab/fgsea#45]
Hi, 
great package!
To calculate the enrichment score in GSEApreranked tool from the broad institute they offer 4 options (classic, weighted, weighted_p2, weighted_p3.)  How are you handling these settings under the hood and are you considering to add these options to your package?

**Comment by assaron** [comment]
I haven't tried Broad's version for a long time, so can't say definetly, but I would guess that corresponds to `gseaParam` being equal 0, 1, 2, 3 respectively. This is the power the weights are raised into, before the enrichment score calculation.

**Comment by stefanCoH** [comment]
thank you for your response. that is exactly what I meant. I appreciate your clarification.
