### ISSUE TITLE
fGSEA for counting data

### ISSUE THREAD

**Issue by Arash-Iranzadeh** [ctlab/fgsea#47]
Hi,

I have done a gene presence absence analysis across two populations. There are some genes that are significantly present in one population. I also have the related GOs of all genes in both populations. Can I use fGSEA to find enriched GOs among the significantly present genes? In this case the "Gene-level statistic" would be the genes p-value. Can fGSEA handles p-values like 2E-98, ...0.01 etc?

Thanks!

**Comment by assaron** [comment]
You can try to this, but then do the log-p-value to get the gene-level stats. However, GSEA was designed to be used with a signed statistic, like a t-statistic or signed log-p-value, so the interpretation should be done carefully.

**Comment by assaron** [comment]
Related to #27
