### ISSUE TITLE
running fgsea

### ISSUE THREAD

**Issue by zal4002** [ctlab/fgsea#49]
I am getting the error message: 
"Error in fmatch(p, names(stats)) : attempt to set an attribute on NULL" 

from running this command:
fgsea(pathways = c5_pathways, stats = as.numeric(My_Data[,2]), nperm = 100)

Anyone know what to do about this?

**Comment by assaron** [comment]
Which version of fgsea are you using? It seems that your stats vector is unnamed which gives you an error, in recent versions the error message is more straightforward.

**Comment by zal4002** [comment]
I installed version 1.8.0 through CRAN.  My columns are names 'symbol' and 'stat'.  Is that the correct implementation?

**Comment by assaron** [comment]
No, it should be a numeric vector `stats` (or any other name) with named elements (defeined `names(stats)` values).

**Comment by zal4002** [comment]
That worked but now my results table consists of 0 observations of 8 variables.
I'm getting a warning message saying:

Warning message:
In fgsea(pathways = c5_pathways, stats = My_Data, nperm = 1000) :
  There are ties in the preranked stats (53.68% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.

I tried using a different .gmt file (kegg and then c7_all) for my pathway data and got the same result.

**Comment by zal4002** [comment]
I'm still not getting useful results, does anyone know what I'm doing wrong?

**Comment by assaron** [comment]
Can you share a reproducible example? It's hard to help without it
