### ISSUE TITLE
Ranking metric ascending or descending

### ISSUE THREAD

**Issue by malaybasu** [ctlab/fgsea#53]
I read the manual but could not figure out what the ranking metric should be, ascending tor descending? In JAVA GSEA, there is an option to sort the gene list based on either ascending to descending metric.

**Comment by assaron** [comment]
What the difference do you expect to see?

**Comment by malaybasu** [comment]
We are trying to figure out the importance of genes based on some network parameters. If the gene list is given with a column of numerical values, what method the software used to rank them. We can generate the number but cannot figure out what FGSEA does. There is no pre-sorted option in the software. If our goal is to give genes most important to least important, what the numerical column be, ascending or descending.
