### ISSUE TITLE
Significance of gene-sets higher with increasing nperm values?

### ISSUE THREAD

**Issue by pabloivan** [ctlab/fgsea#55]
Hi,

A collaborator of mine recommended fgsea to apppy on some microarray data that we have generated. I was really happy that it's very fast. I made a gene set gathering BTMs (Li et al. 2014) + kegg + reactome + hallmark. To my surprise however, when I ran fgsea changing only the number of permutations (from 1000 to 100000) my padj goes from non significant (at 1000 perms they are all over 0.23) to very significant, to the point that with 100000 permutations the first seven processes are signifcant at padj < .05. How come this be? I know from the documentation that the minimum nominal p-value is a function of the nperm parameter.

I'm happy to send my rank file if you need.

This is how I ran fgsea:

```R
# Kegg + Reactome + Hallmark + BTM gene-sets from Msigdb
pathways.kegg.react.hallmark <- gmtPathways("gene-sets/kegg_reactome_hallmark_gene_sets.gmt")

# Load rank file (decreasing log2FC values)
v1.7dpi.rnk <- read.delim(file="ranked/V1_7dpi.rnk", header = T, stringsAsFactors = F)
v1.7dpi.rnk <- deframe(v1.7dpi.rnk)

fgseaRes <- fgsea(pathways=pathways.kegg.react.hallmark, 
                  stats=v1.7dpi.rnk,
                  nperm=100000)
```

only the nperm parameter was changed between runs.

**Comment by assaron** [comment]
In short, adjusted pvalue depends on minimal nominal pvalue, which depends
on nperm. You can switch to fgseaMultilevel function available in the
recent release, which can estimate arbitrarily low p-values. There will be
no such problem.

**Comment by pabloivan** [comment]
Thank for the info Alex. I'll try running `fgseaMultilevel`. 

Maybe the benefit of increasing the `nperm` parameter should be further studied by e.g. comparing experiments with known perturbations/alterations in specific pathways and, based on these results, considering fixing this parameter at a reasonable value, instead of letting the user define this. 

As a reviewer, I wouldn't imagine at first glance that processes appear enriched solely due to an increased permutation parameter, as a higher number of permutations pass the message that only more reliable gene-sets appear enriched–which is clearly not the case for fgsea.

**Comment by assaron** [comment]
No, it's the other way. The process can appear statistically non-significant because of not sufficient `nperm` value. That's part of the reason why we introduced `fgseaMultilevel` which we'll be the default option after we get the paper with the method description out.
