### ISSUE TITLE
fgsea for many rank vectors

### ISSUE THREAD

**Issue by ivokwee** [ctlab/fgsea#62]
Hi. 

I want to compute fgsea for many rank vectors (hundreds, thousands...) with the same genesets. Currently doing it in a loop or actually wrapped mclapply but it would be nice to let fgsea accept a matrix instead of vector for the stats to avoid any overhead. Would this be faster and feasible?

Ivo

**Comment by assaron** [comment]
Hi, 

We thought of this feature but there is no obvious way to make it work faster compared to a simple *lapply.
