### ISSUE TITLE
Ranking the genes from Seurat DE output file

### ISSUE THREAD

**Issue by aaqib-ux** [ctlab/fgsea#66]
I am using this tool for enrichment analysis from DESeq2 results file, where I use Wald statistic for genes prerank. It makes things very easy. 
In Seurat, DESeq2 test doesn't return with Wald statistic values. How to prerank genes for fgsea? DE Output file contains p_val, avg_logFC, pct.1, pct.2 and p_val_adj? 
I am new in this field, sorry I don't know much.

**Comment by assaron** [comment]
There is discussion about fgsea for single-cell in this thread: https://github.com/ctlab/fgsea/issues/50 Hopefully it will answer your question.
