### ISSUE TITLE
fgsea NA values?

### ISSUE THREAD

**Issue by ahdee** [ctlab/fgsea#67]
Hi, fgsea works really well for me however occasionally I get a dataset that has NA for the pval value.  Does anyone know why that is the case? Thanks!

here is an example output.

```
                                                                pathway pval padj          ES NES nMoreExtreme size                                  leadingEdge
 1:                                          BP_AMIDE_BIOSYNTHETIC_PROCESS   NA   NA -0.11664589  NA            0  736 ST8SIA2,PIWIL1,IGF2BP1,GGT5,EEF1A2,SMPD3,...
 2:                                          BP_ANIMAL_ORGAN_MORPHOGENESIS   NA   NA -0.24180857  NA            0  944    COL2A1,DMP1,AMBN,IFITM5,MMP20,COL11A1,...
 3:                                                    BP_AXON_DEVELOPMENT   NA   NA -0.19181135  NA            0  479       SPTA1,DPYSL5,TNN,MYPN,FEZF2,CTNNA2,...
 4:                                 BP_CALCIUM_ION_TRANSMEMBRANE_TRANSPORT   NA   NA -0.23682943  NA            0  285    SLC8A3,TRDN,S100A1,CACNA1E,CALCR,R
```

fgsea_1.12.0

this is the code I run. 
fgsea(stats=glist, pathways=pathways.in , minSize=15, maxSize=50000, nperm=1000)

**Comment by ahdee** [comment]
Update: I think I figured it out according the GSEA FAQ this can happen and increasing the permutation can help.  I increased it from nperm 1000 to 50000 and it seem to work, but I'm afraid of overfitting?  is this a concern.?

**Comment by assaron** [comment]
You probably have unbalanced gene weights (e.g. much more positive compared to negative). GSEA P-value normalized on probability to have the score of the same size and due to unbalanced weights one of them is hard to estimate with small nperm.

Also I recommend switching to the latest version (from GitHub or Bioc3.11), there is no need to set nperm, and these cases are handled better.

**Comment by ahdee** [comment]
@assaron thanks for the explanation.  That all makes so much more sense now! I will try the the latest update.
