### ISSUE TITLE
Cumulative test

### ISSUE THREAD

**Issue by sh105** [ctlab/fgsea#68]
Hi.

I understand that both GSEA and FSEA yield to the same results, but I'm not sure the methodology it uses.

Does it uses Kolmogorov-Smirnov a custom cumulative test or a modified version of Kolmogorov?

Thanks

**Comment by assaron** [comment]
Both use a weight variant of KS test. See FGSEA preprint https://www.biorxiv.org/content/10.1101/060012v2 for details
