### ISSUE TITLE
Issue Installing fgsea for R3.3.1

### ISSUE THREAD

**Issue by slokmanex** [ctlab/fgsea#7]
Hi,
First, thank you for the package. 
I have issues install fgsea. I get the following error (I think it may have to do with GCC version l I am using GCC 4.4):
g++ -std=c++0x -I/home/USE/tools/R-3.3.1/include -DNDEBUG  -I/usr/local/include -I"/home/lseridi/tools/R-3.3.1/library/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=c++0x -I/home/USE/tools/R-3.3.1/include -DNDEBUG  -I/usr/local/include -I"/home/lseridi/tools/R-3.3.1/library/Rcpp/include"   -fpic  -g -O2 -c fastGSEA.cpp -o fastGSEA.o
fastGSEA.cpp: In function ‘Rcpp::IntegerVector combination(const int&, const int&, std::mt19937&)’:
fastGSEA.cpp:318: error: ‘uniform_int_distribution’ is not a member of ‘std’
fastGSEA.cpp:318: error: expected primary-expression before ‘int’
fastGSEA.cpp:318: error: expected ‘;’ before ‘int’
fastGSEA.cpp:324: error: ‘uni’ was not declared in this scope
make: *** [fastGSEA.o] Error 1
ERROR: compilation failed for package ‘fgsea’

Thank you,

**Comment by assaron** [comment]
Yeah, it looks so. If you don't want to update gcc you can try to use one of the fgsea's older version. I think this one should work: https://github.com/ctlab/fgsea/releases/tag/v0.99.7
