### ISSUE TITLE
Identical padj among the top significant pathways

### ISSUE THREAD

**Issue by trezende21** [ctlab/fgsea#70]
Hi,
one thing that caught my attention but I couldn't find an explanation is a reason for identical adjusted pvalues among the most significant pathways. Is this a normal thing to happen? I noticed that now in several fgsea runs.

**Comment by assaron** [comment]
It's normal, that's how BH-adjustment works. For example:
```r
> p.adjust(c(0.1, 0.01, 0.015, 0.02), method = "BH")
[1] 0.10000000 0.02666667 0.02666667 0.02666667
```
