### ISSUE TITLE
struggling to understand fgsea output

### ISSUE THREAD

**Issue by nfancy** [ctlab/fgsea#72]
Hi, Thanks for making this package which made gsea very convenient for R user. Recently, we have done a few gsea using custom gene list from differentially expression results from DESeq2. We used the t-statistics as the ranking parameter. Surprisingly, we see negative ES and NES whereas most of our genes are upregulated (from the custom list), only a handful are downregulated. Can you advise anything?

Best wishes
Nurun

**Comment by assaron** [comment]
Hi,

It's hard to tell without the data. Can you send me an example?

**Comment by nfancy** [comment]
Hi, thanks, I was about to send you the files but then I realised there was a discrepancy of logFC between the result table with and without lfcshrinkage. Many genes changed their direction after the shrinkage hence the difference of up and down-regulated genes came from. Now the direction of ES matches with the numbers of up- or down-regulated genes. But, now I am a bit confused as to which table to use for gsea, with or without shrinkage and if we use the lfcshrink table what should be the rank metric? It does not have the t-statistic. Can we use the sign of logFC multiplied by -log10(unadjusted p value)?

**Comment by assaron** [comment]
It sounds pretty strange to have the direction of regulation to change after shrinkage. Please, check first that there are no problems with your dataset.

Either way, `lfcShrink` function returns table that contains `stat` column which you can use for ranking. Moreover, the values in this column are the same as after `results` function.

**Comment by nfancy** [comment]
Hi, you were right, there were some issues with the annalysis. Thanks for the pointers. You can close this issue if you want.
