### ISSUE TITLE
How to calcuclate the error estimations in returned p-values?

### ISSUE THREAD

**Issue by guidohooiveld** [ctlab/fgsea#77]
Hi,
Thanks again for your continuous work on the FGSEA method!
I likely have missed it (and it is only a minor question), but how can I convert (calculate) the error estimations in p-value calculations when using the multilevel algorithm?

To illustrate (and likely better explain) my question:
using the included example data set and code the following result table is produced:
```
> fgseaRes <- fgsea(pathways = examplePathways, 
+                   stats    = exampleRanks,
+                   eps      = 0.0,
+                   minSize  = 15,
+                   maxSize  = 500)
> 
> 
```
```
> head(fgseaRes[order(pval), ])
                                           pathway         pval         padj
1:                              5990980_Cell_Cycle 6.767965e-27 3.966027e-24
2:                     5990979_Cell_Cycle,_Mitotic 3.738202e-26 1.095293e-23
3:                    5991851_Mitotic_Prometaphase 1.226253e-18 2.395282e-16
4: 5992217_Resolution_of_Sister_Chromatid_Cohesion 3.112834e-17 4.560302e-15
5:                                 5991454_M_Phase 1.053320e-14 1.234491e-12
6:          5991502_Mitotic_Metaphase_and_Anaphase 6.440591e-14 6.290311e-12
     log2err        ES      NES size                              leadingEdge
1: 1.3422338 0.5388497 2.670630  369 66336,66977,12442,107995,66442,19361,...
2: 1.3267161 0.5594755 2.738157  317 66336,66977,12442,107995,66442,12571,...
3: 1.1146645 0.7253270 2.977249   82 66336,66977,12442,107995,66442,52276,...
4: 1.0672100 0.7347987 2.954166   74 66336,66977,12442,107995,66442,52276,...
5: 0.9865463 0.5576247 2.561094  173 66336,66977,12442,107995,66442,52276,...
6: 0.9545416 0.6052907 2.659078  123 66336,66977,107995,66442,52276,67629,...
> 

```

But how do I use the `log2err` values to calculate the error in the returned p-values?
Basically I would like to 'reproduce' the results that are reported in Figure 3 of your FGSEA manuscript posted at bioRxiv ([here](https://t.co/j3VixZOzli?amp=1)). I pasted the figure below.

I am asking because the function `plotGseaTable()` does not seem to return the error in p-value calculations. See at the bottom.

![image](https://user-images.githubusercontent.com/22979991/93228428-bf3e8000-f775-11ea-922f-ba0463d7d8ef.png)

^^^ In the figure (3) above the error in p-value calculations is reported...

![image](https://user-images.githubusercontent.com/22979991/93230676-370daa00-f778-11ea-9a37-80cc90054270.png)

... but this error is not included the the output from `plotGseaTable()` ^^^.
.... generated by this code.
```
PathwaysUp <- fgseaRes[ES > 0][head(order(pval), n=10), pathway]
> topPathwaysDown <- fgseaRes[ES < 0][head(order(pval), n=10), pathway]
> topPathways <- c(topPathwaysUp, rev(topPathwaysDown))
> plotGseaTable(examplePathways[topPathways], exampleRanks, fgseaRes, 
+               gseaParam=0.5)
>
```

Thanks!

**Comment by assaron** [comment]
Hi,

The errors are reported on log2 scale. To convert them to log10 scale (as was done in the figure) just divide the error by `log2(10)`. For example, on log2 scale the error for the first pathway is 1.34. And `1.34/log2(10)`  is equal to 0.40. 

To clarify, log2err of 1.34 means that we estimate 95% confidence interval (plus and minus two sigma) to be from 6.77e-27/2**(2*1.34) to 6.77e-27*2**(2*1.34), that is from 1.06e-27 to 4.34e-26

**Comment by guidohooiveld** [comment]
Thanks for your quick and clear explanation!
