### ISSUE TITLE
scoreType question

### ISSUE THREAD

**Issue by pstew** [ctlab/fgsea#79]
How are the ranks treated for `scoreType = "pos"` ? At one point in the code you sort by decreasing values. For `scoreType = "pos"`, does this mean the largest value is the first rank? I just want to make sure the smallest value is not the first rank (e.g. it is not counting upwards from 1 for the ranks). Does this then mean the smallest value is the first rank for `scoreType = "neg"`? Thanks!

**Comment by assaron** [comment]
Ranks are treated in the same way, independent of `scoreType`: they are always sorted from largest positive to largest negative values. What `scoreType` does is changes which extremum of the enrichment curve is used as an enrichment score value: `pos` -- for maximum (always non-negative), `neg` -- for minimum (always non-positive), `std` -- whichever from max and min has the greatest absolute value. Consequently, the p-value calculation is changed a bit, with `pos` and `neg` leading to single-end p-value, as opposed to the sort-of two-tailed standard P-value.

**Comment by pstew** [comment]
Thank you! I really appreciate the quick response. Thank you for the great, easy to use package!
