### ISSUE TITLE
Results of fgsea

### ISSUE THREAD

**Issue by icTAIR** [ctlab/fgsea#8]
Hi there,

I installed "fgsea" and input a list of pre-ranked genes.
Those genes were selected based on breast cancer. 
The weights were t score by comparing the expression between ER+ and ER- patients.
When I ran fgsea and the result returned 18 pathways.
Can I tell which pathways are enriched in ER+ patients and which are enriched in ER- ones?

Do you have any suggestion on the weights? Which kind of statistic data is the best weight for fgsea?

Thank you.

**Comment by ToledoEM** [comment]
Hi icTAIR, 
Those questions are pertinent to the bases of the GSEA it self. I would recommend you to read the original paper of GSEA (https://www.ncbi.nlm.nih.gov/pubmed/16199517) , specially the supplemental material that explain the math behind it weights. Also I highly recommend to read the documentation in the broad institute (http://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Main_Page).

Best,
