### ISSUE TITLE
Error in if (maxP > -minP) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by nfancy** [ctlab/fgsea#82]
Hi 
Thank you very much for the package. I've recently updated the version and getting this error. Can you please shade some light?

Here are my command and error:

```
database_list <- list.files(database_dir, pattern = ".gmt", full.names = TRUE)
pathways <- fgsea::gmtPathways(database_list[1])

de <- read.delim("de_table.tsv")
ranked_gene <- de %>% 
  mutate(stat = sign(logFC)* -log10(padj)) %>%
  dplyr::select(gene, stat) %>% 
  arrange(desc(stat)) %>%
  tibble::deframe()

fgseaRes <- fgsea::fgseaSimple(pathways=pathways, stats=ranked_gene, nperm = 1000)

Error in if (maxP > -minP) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam,  :
  There are ties in the preranked stats (3.77% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.
```

Thanks in advance.

**Comment by assaron** [comment]
Can you please post your data, so I can reproduce the error?

**Comment by nfancy** [comment]
hi, the data is attached. This is the command that gives me the error message:

```
> fgseaRes <- fgsea::fgsea(pathways=geneset, stats=ranked_gene,
+                          nperm=1000, maxSize = 1000)
Error in if (maxP > -minP) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In fgsea::fgsea(pathways = geneset, stats = ranked_gene, nperm = 1000,  :
  There are ties in the preranked stats (3.57% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.
```
However, later I figured out, the following command runs the function without an error. Can you please explain what does gseaParam do?

```
fgseaRes <- fgsea::fgsea(pathways=geneset, stats=ranked_gene,
+                          nperm=1000, maxSize = 1000, gseaParam = 0)
Warning message:
In fgsea::fgsea(pathways = geneset, stats = ranked_gene, nperm = 1000,  :
  There are ties in the preranked stats (3.57% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.
```
Many thanks for your response.

[data.zip](https://github.com/ctlab/fgsea/files/5478489/data.zip)

**Comment by assaron** [comment]
This happens due to an infinite value in your `ranked_gene` stats. Setting `gseaParam` to zero keeps the order, but sets all the stats to 1, by raising all the values in to the power of zero.

We'll add a check, so that the error message will be more apropriate.

**Comment by assaron** [comment]
We've added the check in 07f86379b5c6fcbeca82e2f6937ec527eae95b42

**Comment by nfancy** [comment]
thanks a lot. This brings another question though. What is the appropriate gseaParam value?

**Comment by assaron** [comment]
This parameters controls how gene weights are considered: the weights absolute values are raised to the power of `gseaParam` after ordering. `gseaParam` of zero make all weight equal, resulting in a Kolmogorov-Smirnov test, `gseaParam` of one make the weights to be used as is. Usually there is no need to change it from the default value of 1, unless you use some weird metrics or have a specific reason in mind.
