### ISSUE TITLE
p-value calculation using fgsea fgseaSimple function

### ISSUE THREAD

**Issue by mengyuankan** [ctlab/fgsea#83]
Hi,

I used the fgsea fgseaSimple function to compute p-values by specifying nperm=10000

I realized that the p-values are not computed using the denominator of #permutations (i.e. 10000). I read into the codes and found the corresponding codes for p-value calculation here (Line 457-458 in fgsea.R):
pval=min((1+sum(leEs)) / (1 + sum(leZero)), (1+sum(geEs)) / (1 + sum(geZero)))

I don't quite get the coding here. From my understanding, because the permutations are independent, we could not exclude permutations where the permutated ES goes to the other direction. I think to use #permutations as the denominator, the nominators could be coded as: 1. if actual ES<0, the number of permutations where permutated ES <= actual ES and 2. if actual ES>=0, the number of permutations where permutated ES >= actual ES. Would you please explain a bit the rationale for not using the total number of permutations as the denominator? 

Thank you very much!

Mengyuan

**Comment by assaron** [comment]
The P-value calculation follows the original paper by Subramanian. It was developed to adjust for cases when the distribution of enrichment scores is not symmetrical (for example there are more positive ES than negative).

**Comment by mengyuankan** [comment]
Thanks for your reply. Would you please direct me to your original paper so that I can take a look?

**Comment by assaron** [comment]
Here it is (and it's not our lab): https://www.pnas.org/content/102/43/15545 More details can be found in supplementary there

**Comment by mengyuankan** [comment]
Thanks!

I found this statement from their paper: "Estimate nominal P value for S from ESNULL by using the positive or negative portion of the distribution corresponding to the sign of the observed ES(S)."

I am wondering that, because you take the minimum p-value from both signs, is there any chance that the sign of actual ES is not consistent with the sign where the minimum p-value is derived. For example, the observed ES is a positive number whereas (1+sum(leEs)) / (1 + sum(leZero)) happens to be the minimum.

**Comment by assaron** [comment]
P-value is calculated for the observed sign of ES(S). If it's positive then geES is used for nominator, if negative then leES

**Comment by mengyuankan** [comment]
Would you please direct me to the lines of codes where the p-value is computed in your fgsea.R, if the line 457-458 pval=min((1+sum(leEs)) / (1 + sum(leZero)), (1+sum(geEs)) / (1 + sum(geZero))) is not the correct place?
Thanks!

**Comment by assaron** [comment]
The lines are actually 686-687, but yes, this looks suspicious. Thanks for noticing! I'll get back to you after some investigation

**Comment by mengyuankan** [comment]
Yeah, actually Lines 686-687 were also where I've noticed. I think they also take pmin which is to choose the minimum value. Thank you so much for looking into that!

**Comment by assaron** [comment]
I've checked again, the calculation is correct. For positive ES the value of `(1+nLeEs) / (1 + nLeZero)` is greater than one and the other value will be less then one, so the latter will be the minimum.

It was a trick so clever, that I forgot about it after a while :) Still, thanks again for noticing, we'll try to change it into a more obvious way.

**Comment by mengyuankan** [comment]
Ah, yes! Thanks for the explanation. Now I get the trick here!
