### ISSUE TITLE
Which testing method is the best?

### ISSUE THREAD

**Issue by xihuiyin** [ctlab/fgsea#85]
I am trying to test the DEGs between the clusters for my scRNAseq data in Seurat and I've noticed some fgsea tutorials out there that use MAST, while others use Wilcoxon. Is there any preferred method of testing the DEGs to use for fgsea analysis? Which would be better, Wilcoxon or MAST?

**Comment by ToledoEM** [comment]
I do not think this is a question about fgsea

**Comment by xihuiyin** [comment]
> I do not think this is a question about fgsea

I would like to know which testing method yields less false negatives/positives with fgsea.

**Comment by assaron** [comment]
I'm not working much with single-cell data, so can't really comment. You can either check out the thread https://github.com/ctlab/fgsea/issues/50 or ask this question on a forum like biostars.
