### ISSUE TITLE
scoreType argument

### ISSUE THREAD

**Issue by pascaltimshel** [ctlab/fgsea#87]
hi fgsea dev team!

The functions `fgseaSimple()` and `fgseaMultilevel()` have a `scoreType` argument documented as:
`scoreType: This parameter defines the GSEA score type. Possible options are ("std", "pos", "neg")`

This docstring isn't very helpful because I can't find any documentation for "GSEA score type" for the original GSEA software. I've also looked through the fgsea source code, but I still don't understand what the argument does.

**Q1**: can you explain what the GSEA score type parameter does? (Can you refer to a description of "GSEA score type" in the original GSEA software?)
**Q2**: when is it appropriate to use e.g. "pos" instead of "std"?
**Q3**: can you provide an example showing the differences in the results/interpretation when running with "std", "pos" and "neg"? 

Thanks for creating this amazing and blazing fast piece of software!

**Comment by assaron** [comment]
It's not a parameter from the original GSEA paper. It was developed by request for one-tailed tests, when you are interested in either only positive enrichment ("pos") or negateive ("neg"). You can check out discussion here: https://github.com/ctlab/fgsea/issues/27

There are two particular use cases: 
1) When your stats vector is  positive (not signed, as usual), for example, the absolute value of logFC, and you're interested in deregulated pathways that has more positive logFC compared to a random pathway
2) When your stats vector is not balanced, for example, when you do differeitntial expression in scRNA-seq between a single cluster and all other clusters. Usually, there are some specific genes (with high positive metric), but no negative specific genes (so there are no highly negative values, only somewhat negative). Similarly, you're looking for a pathways "positively" specific to the cluster, and there are no "negatively" specific pathways. 

Some people would fine it useful, but we didn't do any analysis to show what are properties of this non-standard score types.

**Comment by pascaltimshel** [comment]
thank you @assaron !
