### ISSUE TITLE
fgsea vs liger: what is the difference in the results?

### ISSUE THREAD

**Issue by pascaltimshel** [ctlab/fgsea#88]
hi @assaron and the rest of the team,

I've been using fgsea for a while now and really love it. I previously used another gsea-based method called liger (https://github.com/JEFworks/liger). Since both liger and fgsea claim to be a faster implementation of the original GSEA, I wonder what the differences between the methods are. 

### liger vs fgsea comparison
The developer of liger published a [comparison](https://github.com/JEFworks/liger/blob/master/vignettes/comparison.pdf) between liger and fgsea, and found some important differences:
_What we can see is that `liger` detected a significant lack of genes in this gene set among the most highly ranked genes as noted by the positive `edge` but negative `sscore`. This particular type of enrichment testing may be important if we want to make claims about certain gene sets never being highly differentially expressed (depleted in representation) but are not necessarily down-regulated. **As `fgsea` does not detect such patterns**,...
....
In conclusion, `fgsea` provides a very fast test for gene sets where ranked gene values are appropriate. Both `fgsea` and `liger` offer very comparable results when looking for significantly upregulated or downregulated gene sets...._

### My questions
**Q1**: are there any fundamental differences between liger, fgsea and GSEA? (Except fsgea is _much_ much faster). 
**Q2**: what patterns is it liger (and the original GSEA method) detects, but not fgsea? And why does fgsea not detect them? ("_As `fgsea` does not detect such patterns_", see below example)
**Q3**: why are the enrichment score (and enrichment plots) different between liger and fgsea? E.g. on the last plot in the below example, fgsea score is ~0.6, while liger score is ~3500. 
**Q4**: why does fgsea not report 'edge values"?
**Q5**: do you have plans on updating `plotEnrichment` so allow for different styles? I think users would like generate plots more similar to the output of liger. (see also https://github.com/ctlab/fgsea/issues/29)

### comparison example/code

``` r
library(fgsea)
#> Loading required package: Rcpp
library(liger)
#> Warning: package 'liger' was built under R version 3.6.2

# example pathways from fgsea
data(examplePathways)
data(exampleRanks)

# run fgsea
fgseaRes <- fgsea(pathways = examplePathways, 
                  stats = exampleRanks,
                  nperm=1000,
                  BPPARAM=BiocParallel::MulticoreParam(workers = 1))


# run liger
ligerRes <- iterative.bulk.gsea(exampleRanks, 
                                set.list=examplePathways,
                                n.rand = c(100, 1000)
)
#> initial: [1e+02 - 619] [1e+03 - 255] done



# # compare 
fgseaP <- fgseaRes$padj; names(fgseaP) <- fgseaRes$pathway
fgseaP <- fgseaP[names(examplePathways)]
ligerP <- ligerRes$q.val; names(ligerP) <- rownames(ligerRes)
ligerP <- ligerP[names(examplePathways)]

# maximal difference (most inconsistent) between methods
diff <- abs(-log10(fgseaP) - -log10(ligerP))
diff <- sort(diff, decreasing=TRUE)
# pick most inconsistent
gs <- names(diff)[1]
print(fgseaP[gs])
#> 5991096_GTP_hydrolysis_and_joining_of_the_60S_ribosomal_subunit 
#>                                                       0.9928193
print(ligerP[gs])
#> 5991096_GTP_hydrolysis_and_joining_of_the_60S_ribosomal_subunit 
#>                                                      0.01236138
# fgsea
plotEnrichment(examplePathways[[gs]], exampleRanks) 
```

![](https://i.imgur.com/1XDHLWg.png)

``` r
# liger
gsea(exampleRanks, examplePathways[[gs]])
```

![](https://i.imgur.com/07NewCp.png)

    #> [1] 0.0068

    # make comparable: restrict to gene sets for which `liger` detects a consistent `sscore` and `edge`
    vi <- ligerRes$sscore * ligerRes$edge > 0
    consistentGs <- rownames(ligerRes)[vi]

    # pick a significant gene set and compare
    gs <- names(which(fgseaP[consistentGs]==min(fgseaP[consistentGs])))[1]
    print(fgseaP[gs])
    #> 5990976_Assembly_of_the_pre-replicative_complex 
    #>                                      0.03140203
    print(ligerP[gs])
    #> 5990976_Assembly_of_the_pre-replicative_complex 
    #>                                      0.01236138
    # fgsea
    plotEnrichment(examplePathways[[gs]], exampleRanks) 

![](https://i.imgur.com/rGgKIdk.png)

``` r
# liger
gsea(exampleRanks, examplePathways[[gs]])
```

![](https://i.imgur.com/O9KDlcg.png)

    #> [1] 6e-04

    # Session info
    sessioninfo::session_info()
    #> ─ Session info ──────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 3.6.1 (2019-07-05)
    #>  os       macOS Catalina 10.15.7      
    #>  system   x86_64, darwin15.6.0        
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       Europe/Copenhagen           
    #>  date     2021-02-19                  
    #> 
    #> ─ Packages ──────────────────────────────────────────────────────────────
    #>  package      * version date       lib source        
    #>  assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
    #>  BiocParallel   1.18.1  2019-08-06 [1] Bioconductor  
    #>  cli            2.3.0   2021-01-31 [1] CRAN (R 3.6.2)
    #>  colorspace     1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
    #>  crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
    #>  data.table     1.12.2  2019-04-07 [1] CRAN (R 3.6.0)
    #>  digest         0.6.20  2019-07-04 [1] CRAN (R 3.6.0)
    #>  dplyr          0.8.3   2019-07-04 [1] CRAN (R 3.6.0)
    #>  evaluate       0.14    2019-05-28 [1] CRAN (R 3.6.0)
    #>  fastmatch      1.1-0   2017-01-28 [1] CRAN (R 3.6.0)
    #>  fgsea        * 1.10.1  2019-08-21 [1] Bioconductor  
    #>  fs             1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
    #>  ggplot2        3.3.0   2020-03-05 [1] CRAN (R 3.6.0)
    #>  glue           1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
    #>  gridExtra      2.3     2017-09-09 [1] CRAN (R 3.6.0)
    #>  gtable         0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
    #>  highr          0.8     2019-03-20 [1] CRAN (R 3.6.0)
    #>  htmltools      0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
    #>  knitr          1.25    2019-09-18 [1] CRAN (R 3.6.1)
    #>  labeling       0.3     2014-08-23 [1] CRAN (R 3.6.0)
    #>  lattice        0.20-38 2018-11-04 [1] CRAN (R 3.6.1)
    #>  liger        * 2.0.1   2021-01-25 [1] CRAN (R 3.6.2)
    #>  magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.0)
    #>  Matrix         1.2-17  2019-03-22 [1] CRAN (R 3.6.1)
    #>  matrixStats    0.55.0  2019-09-07 [1] CRAN (R 3.6.0)
    #>  munsell        0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
    #>  pillar         1.4.2   2019-06-29 [1] CRAN (R 3.6.0)
    #>  pkgconfig      2.0.2   2018-08-16 [1] CRAN (R 3.6.0)
    #>  purrr          0.3.2   2019-03-15 [1] CRAN (R 3.6.0)
    #>  R6             2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
    #>  Rcpp         * 1.0.2   2019-07-25 [1] CRAN (R 3.6.0)
    #>  reprex         1.0.0   2021-01-27 [1] CRAN (R 3.6.2)
    #>  rlang          0.4.6   2020-05-02 [1] CRAN (R 3.6.2)
    #>  rmarkdown      1.15    2019-08-21 [1] CRAN (R 3.6.0)
    #>  rstudioapi     0.13    2020-11-12 [1] CRAN (R 3.6.2)
    #>  scales         1.0.0   2018-08-09 [1] CRAN (R 3.6.0)
    #>  sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
    #>  stringi        1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
    #>  stringr        1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
    #>  tibble         2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
    #>  tidyselect     1.1.0   2020-05-11 [1] CRAN (R 3.6.2)
    #>  withr          2.4.1   2021-01-26 [1] CRAN (R 3.6.2)
    #>  xfun           0.9     2019-08-21 [1] CRAN (R 3.6.0)
    #>  yaml           2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by assaron** [comment]
I didn't dig deep into liger, so can't properly answer your questions. 

> Q1: are there any fundamental differences between liger, fgsea and GSEA? (Except fsgea is much much faster).

`fgsea` estimates **the same** P-values as the original software by Broad. `liger` calculates something different.

> Q2: what patterns is it liger (and the original GSEA method) detects, but not fgsea? And why does fgsea not detect them? ("As fgsea does not detect such patterns", see below example)

Again, I didn't test liger but from the vignette, in particulate the part that your cite, it follows that different patterns are detected. In particular, GSEA was designed to detect *asymetric* patterns: positively or negatively enriched. Symmetric patterns in GSEA gives you zero enrichment score, which won't be significant. 

However, some symmetric patterns can be found in fgsea if you first get an absolute value of gene statistics and then use one-tailed score variant (scoreType=pos or scoreType=neg, depending on the direction you're interested in).

Can't comment anything on Q3 and Q4.

> Q5: do you have plans on updating plotEnrichment so allow for different styles? I think users would like generate plots more similar to the output of liger. 

Not really. We welcome any pull requests the would make `plotEnrichment` more tweakable, but that has low priority for us.

**Comment by pascaltimshel** [comment]
thank you very much @assaron !
