### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by lixin4306ren** [ctlab/fgsea#9]
> install_github("ctlab/fgsea")
Downloading GitHub repo ctlab/fgsea@master
from URL https://api.github.com/repos/ctlab/fgsea/zipball/master
Installing fgsea
'/opt/apps/R/3.3.2/lib64/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpeIaZPo/devtools9dd13505afcd/ctlab-fgsea-29b4e3c'  \
  --library='/opt/apps/R/3.3.2/lib64/R/library' --install-tests

* installing *source* package ‘fgsea’ ...
** libs
g++ -std=c++0x -I/opt/apps/R/3.3.2/lib64/R/include -DNDEBUG  -I/opt/apps/bzip2-1.0.6/include -I/opt/apps/xz/5.2.2/include -I/opt/apps/pcre/8.39/include -I/opt/apps/curl/7.52.1/include -I"/opt/apps/R/3.3.2/lib64/R/library/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=c++0x -I/opt/apps/R/3.3.2/lib64/R/include -DNDEBUG  -I/opt/apps/bzip2-1.0.6/include -I/opt/apps/xz/5.2.2/include -I/opt/apps/pcre/8.39/include -I/opt/apps/curl/7.52.1/include -I"/opt/apps/R/3.3.2/lib64/R/library/Rcpp/include"   -fpic  -g -O2 -c fastGSEA.cpp -o fastGSEA.o
fastGSEA.cpp: In function ‘Rcpp::IntegerVector combination(const int&, const int&, std::mt19937&)’:
fastGSEA.cpp:318: error：‘uniform_int_distribution’ is not member of ‘std’ 
fastGSEA.cpp:318: error：expected primary-expression before ‘int’
fastGSEA.cpp:318: error：expected ‘;’ before ‘int’
fastGSEA.cpp:324: error：‘uni’ undefined
make: *** [fastGSEA.o] error 1
ERROR: compilation failed for package ‘fgsea’
* removing ‘/opt/apps/R/3.3.2/lib64/R/library/fgsea’
ERROR: Command failed (1)

**Comment by assaron** [comment]
Please see this issue: https://github.com/ctlab/fgsea/issues/7 

You need to use newer gcc (or older fgsea).

**Comment by lixin4306ren** [comment]
But, my gcc version is "gcc (GCC) 6.2.0". Is it still not new enough?

**Comment by assaron** [comment]
Hm, 6.2.0 should be good. Are you sure your R installation uses it? You can try to force the version like in here: http://stackoverflow.com/a/1618618

Also, do you have an older g++ installed somewhere? Something before 4.5. And, please, check g++ (not gcc) version too. I guess they could be different.

**Comment by lixin4306ren** [comment]
Thanks. Yes, you are right, the R was using the old one. I changed the path and it worked. Thanks again.
