### ISSUE TITLE
the same results with descending and ascending order of gene list

### ISSUE THREAD

**Issue by ncusk** [ctlab/fgsea#92]
Hi,
 Thanks for the nice tool. fgsea seems generate the same results with descending and ascending order of gene list. here is my code:

##
df <- df[order(-df$statistic), ]
rank <- df$statistic
names(rank) <- df$entrz_ID
my_pathways <- reactomePathways(names(rank))
gsea.test <- fgsea(pathways = my_pathways, 
                  stats    = rank,
                  minSize  = 15,
                  maxSize  = 500)

when I use 
##
df <- df[order(df$statistic), ]

and run fgsea again, it generates the identical results. would you please explain why?

thanks

**Comment by assaron** [comment]
Gene are always sorted internally by the gene-level statistic.

**Comment by ncusk** [comment]
internally sorted by descending or ascending?

**Comment by assaron** [comment]
In descending order

**Comment by ncusk** [comment]
Thanks
