### ISSUE TITLE
NA in pval column

### ISSUE THREAD

**Issue by pstew** [ctlab/fgsea#97]
Hello, I am running fgsea on some RNA-seq data with parameters minSize = 15, maxSize = 500, scoreType = "std", and eps = 1E-50.  I am getting some NA's in the pval results column. These gene sets are a little on the large side, but they are under my maxSize. They seem to be the only ones with this issue. Below is the data sorted so that you can see the NA's. Could you help me understand what the issue might be? Thank you.

<img width="876" alt="Screen Shot 2021-07-06 at 1 26 29 PM" src="https://user-images.githubusercontent.com/5620536/124642392-cb5b1180-de5d-11eb-8dc3-d462221816dd.png">

**Comment by assaron** [comment]
Hi, there should be a warning message, describing why you get NAs and
probably even a way fix the problem. Likely, your gene-level statisitic has
a skewed distribution.

**Comment by pstew** [comment]
Ahhh, my knitr settings were suppressing the warning messages. I see it now. Thank you.
